name=Preferences
version=2.3.0
license=MIT
author=Volodymyr Shymanskyy
maintainer=Volodymyr Shymanskyy <vshymanskyi@gmail.com>
sentence=Preferences library for ESP8266, RP2040, Realtek Ameba and Particle Gen3. Compatible with ESP32 API.
paragraph=
category=Data Storage
url=https://github.com/vshymanskyy/Preferences
architectures=*
